[book]
authors = ["bjones1"]
language = "en"
multilingual = false
src = "src"
title = "mdbook template"

# This is required in order to run CodeChat on mdbook files.
[preprocessor.CodeChat]

# Optional: `lexer_for_glob` is a dict of ``{glob_: str, lexer_alias: str}``,
# which uses ``lexer_alias`` (e.g. a lexer's `short name
# <http://pygments.org/docs/lexers/>`_) to analyze any file which matches the
# given glob-style pattern (e.g. `glob
# <https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match>`_).
[preprocessor.CodeChat.lexer_for_glob]
# Some (commented-out) examples:
#"*.js" = "JavaScript"
#"*.css" = "CSS"